on: [push, pull_request]
name: pREST CI

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:latest
    env:
      PREST_PG_HOST: postgres
      PREST_PG_DATABASE: prest-test
      PREST_PG_USER: postgres
      PREST_PG_PASS: postgres
      PREST_SSL_MODE: disable
      PREST_CONF: ./testdata/prest.toml
      PREST_MIGRATIONS: ./testdata/migrations
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: prest-test
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install -y postgresql-client

      - name: Setup Database
        env:
          PGPASSWORD: postgres
        run: |
          psql -h $PREST_PG_HOST -p $PREST_PG_PORT -U $PREST_PG_USER -c "DROP DATABASE IF EXISTS \"$PREST_PG_DATABASE\";"
          psql -h $PREST_PG_HOST -p $PREST_PG_PORT -U $PREST_PG_USER -c "CREATE DATABASE \"$PREST_PG_DATABASE\";"
          psql -h $PREST_PG_HOST -p $PREST_PG_PORT -U $PREST_PG_USER -d $PREST_PG_DATABASE -f ./testdata/schema.sql

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install Dependencies
        run: |
          echo "Installing DeepSource"
          sed -i 's/azure\.//' /etc/apt/sources.list
          apt-get update
          curl https://deepsource.io/cli | sh
          echo "Installing GolangCI Lint"
          curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.15.0
          apt -y install gcc-multilib
          git config --global --add url."git@github.com:prest".insteadOf "https://github.com/prest"
          go get -v -d ./...
          go get -v github.com/inconshreveable/mousetrap
          go get golang.org/x/tools/cmd/cover
          go get github.com/mattn/goveralls

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.12.2/migrate.linux-amd64.tar.gz | tar xvz
          mv migrate.linux-amd64 /usr/bin/migrate
          which migrate

      - name: pREST Test
        run: |
          // curl -sfL https://git.io/goreleaser | sh -s -- check
          env go run ./cmd/prestd/main.go migrate --url="$DB_URL" up
          env go run ./cmd/prestd/main.go migrate --url="$DB_URL" up auth
          env go test -race -covermode=atomic -coverprofile=coverage.out ./...
